{"created_at": "2022-08-27 12:28:09.856360", "build": null, "status": "unhealthy", "report": {"datastore_classic": {"desc": "Datastore Classic", "results": {"TestDatastoreClassic.test_healthy": {"desc": "Test API self-reports as healthy", "args": [], "outcome": "passed", "error_msg": ""}}, "status": "healthy"}, "iati_data_dump": {"desc": "IATI Data Dump", "results": {"TestIATIDataDump.test_metadata": {"desc": "Test metadata was created in the last 24 hours", "args": [], "outcome": "failed", "error_msg": "self = <test_iati_data_dump.TestIATIDataDump object at 0x7ffbaae83690>\n\n    def test_metadata(self):\n        \"\"\"\n        Test metadata was created in the last 24 hours\n        \"\"\"\n        url = \"https://gist.githubusercontent.com/\" + \\\n              \"codeforIATIbot/efd190029713c6775c43962444dcb8df/\" + \\\n              \"raw/metadata.json\"\n        resp = requests.get(url)\n        assert resp.status_code == 200\n        j = resp.json()\n        created_at = j[\"created_at\"]\n        delta_since = (datetime.now(pytz.utc) - date_parse(created_at))\n>       assert delta_since.days == 0\nE       assert 3 == 0\nE        +  where 3 = datetime.timedelta(days=3, seconds=62696, microseconds=828430).days\n\ntests/test_iati_data_dump.py:23: AssertionError"}}, "status": "unhealthy"}}}